### PR TITLE
add crash fix for solocraft , add mod-premium

### PR DESCRIPTION
**Pull request by milestorme**
mod premium still needs mailbox fix but all else is working and tested, temp crash fix for solocraft until your update

### CODE REVIEW

**Comment by talamortis** [comment]
can you fix travis please

**Comment by milestorme** [comment]
> can you fix travis please

Travis failed on mod-telenpc I didn’t actually do anything to that one , I’ll see what I can do

**Comment by talamortis** [comment]
Ok, i have pushed a fix. Lets see if it compiles fine and then ill merge yours :)

**Comment by milestorme** [comment]
`/home/travis/build/milestorme/oregoncore/modules/mod-TeleNPC2/src/sc_npc_teleport.cpp: In member function ‘bool nsNpcTel::CatDest::IsAllowedToTeleport(Player*) const’:
934/home/travis/build/milestorme/oregoncore/modules/mod-TeleNPC2/src/sc_npc_teleport.cpp:163:78: error: ‘error_log’ was not declared in this scope
935     error_log("Invalid flag (category: %u). Important problem...", GetCatID());
936                                                                              ^`

Could have something to do with the core logging changes pushed the other day , module might need update

**Comment by milestorme** [comment]
Oh wait I just noticed that was in my Travis , weird your Travis errors before loading core on database

**Pull request merged**
