### PR TITLE
Upload module NPC Gurubashi Arena Theme Generator

### PR DESCRIPTION
**Pull request by ekzobam**

### CODE REVIEW

**Comment by talamortis** [comment]
Thanks for the module. Are you able to put the spawns in a Unordered_map that way it doesn't query the DB each time.

If not ill still merge and then update it at a later date.

**Comment by yuanf225** [comment]
2020-08-11 11:11:46 Cannot execute file 2020_07_25_npc_gurubashi_theme.sql, size: 21108: Unknown column 'ENTER_NPC_ID_HERE' in 'field list'
I am using the new core and DB, but it will report an error and cannot be automatically updated. Do I need to manually update to worldDB?

**Comment by ekzobam** [comment]
@yuanf225 change ENTER_NPC_ID_HERE in sql file to npc id and use automatically updater

**Comment by yuanf225** [comment]
@ekzobam Sorry, When I checked back, TY

**Pull request merged**
